export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";

export const CREATE_COLUMN_SUCCESS = "CREATE_COLUMN_SUCCESS";
export const DELETE_COLUMN_SUCCESS = "DELETE_COLUMN_SUCCESS";
export const REORDER_COLUMN_SUCCESS = "REORDER_COLUMN_SUCCESS";

export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
